# datasource connection properties
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.name=m3_final_project
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.schema=forum

jwt.header=Authorization
jwt.base64-secret=${JWT_BASE64_SECRET}
jwt.secret=${JWT_SECRET}
jwt.expiration=604800
jwt.token-validity-in-seconds=${JWT_TOKEN_VALIDITY_IN_SECONDS}
jwt.token-validity-in-seconds-for-remember-me=${JWT_TOKEN_VALIDITY_IN_SECONDS_FOR_REMEMBER_ME}
jwt.route.authentication.path=/login
jwt.route.authentication.refresh=/refresh

server.error.include-stacktrace=never

server.port=${PORT:9000}
